ALL: GOPHERD.TSK

GOPHERD.TSK: GOPHERD.OBJ LINK.CMD GOPHERD.ODL LB:[1,1]IPLIB.OLB \
	LB:[1,1]IPBP2.OLB LB:[1,1]BQTBP2.OLB
	TKB @LINK

GOPHERD.OBJ: GOPHERD.B2S LB:[1,1]INET.B2S LB:[1,1]BQTLIB.B2S
	BP2 GOPHERD

CLEAN:
	-PIP *.LOG;*,*.TSK;*,*.OBJ;*,*.STB;*,GOPHERD.MAP;*,*.CRF;*/DE
	-PIP MAKEFILE.,*.CMD/PU

PURE:
	-PIP *.B2S/PU
